#Word2Vec

In [ ]:
import os, zipfile #解壓縮套件
if not os.path.exists("data"):
  f = zipfile.ZipFile("pttsmalldata.zip")
  f.extractall("./data")
  f.close()

In [ ]:
import glob, json
import pandas as pd
contents = []
for fn in glob.glob("data/pttsmalldata/*.json"):
  with open(fn, "r", encoding="utf-8") as f:
    data = json.load(f)
    contents.append(data["post_content"])
  df = pd.DataFrame({"contents": contents})
df.tail()

                                                contents
19995  \n\n上個圖很難嗎？\n你他媽倒是上個圖啊！\n那個到底是不是鄭伊健啊\n有沒有人知道？？...
19996  \n\n尤其是那種又肥又矮又醜又臭又窮又心理扭曲的肥宅\n\n這種噁心的穢物真的不應該存在這...
19997  \n※ 八卦板務請到 GossipPicket 檢舉板詢問\n※ a.張貼問卦請注意，充實文...
19998  \n我看到一個直播主\n\n一直講現煮時現煮時\n\n隆免柯魯啊\n\n哇賊哇賊\n\n歐罵...
19999  \n今天中午\n上公司的課程訓練\n就吃公司提供的免費便當\n真是開心\n\n但裡面竟然有\...

In [ ]:
df = df.head(10)
df

                                            contents
0  \n安安\n\n\n美劇絕命毒師裡面 到後期老白殺人都用溶解屍體 把屍體藏起來\n\n\n想...
1  \n板上的30nm BMI39.87+的中秋胖魯宅們\n晚上好\n\n稍早阿肥回到家中\n一...
2  \n大家好~ 大家晚安!\n\n小弟薩到對面的女同事\n\n想說趁現在買一送一趕緊獻上一杯我...
3  \n\n\n是醬子的\n\n本城武不知為何\n\n睡前沒尻尻 當晚我看是不用睡而且會很難受\...
4  \n\n之前一直聽身邊果粉歌頌Mac多棒多好\n就想說買個二手Mac體驗看看\n應該不會很貴...
5  \n大家晚上好\n中秋好\n\n很久沒有半夜發文了\n很久沒有跟各位廢宅廝混了\n\n想請教...
6  \n\n1.媒體來源: ETtoday新聞雲\n\n2.記者署名 :  記者鄒鎮宇／桃園報導...
7  \n之前加入一個學長創的：考研究所互相加油群組\n\n說什麼會定期發考古題和解題\n\n結果...
8  \n乳提\n\n肥肥我要成為大魔導士了\n\n開始有種想用交友軟體的念頭\n\n但又覺得用了...
9  \n依稀記得以前學生時期搭捷運的時候，\n\n不管是書包多麼重、打球多麼累，\n\n在捷運上...

In [ ]:
import jieba #中文分詞套件
from urllib.request import urlretrieve
url = "https://github.com/fxsjy/jieba/raw/master/extra_dict/dict.txt.big"
urlretrieve(url, "dict.txt.big")
jieba.set_dictionary("dict.txt.big")

In [ ]:
import re
punct = set(u''':!),.:;?]}¢'"、。〉》」』】〕〗〞︰︱︳﹐､﹒﹔﹕﹖﹗﹚﹜﹞！），．：；？｜｝︴︶︸︺︼︾﹀﹂﹄﹏､～￠々‖•·ˇˉ―--′’”([{£¥'"‵〈《「『【〔〖（［｛￡￥〝︵︷︹︻︽︿﹁﹃﹙﹛﹝（｛“‘-—_…~/ －＊➜■─★☆=@<>◉é''')
#去掉全型標點符號
def process(content):
  content = re.sub(r'https?:\/\/.*[\r\n]*', '', content)
  content = " ".join(filter(lambda x: x not in punct, jieba.cut(content)))
  return content
content_cut = df["contents"].apply(process)

Building prefix dict from /content/dict.txt.big ...
DEBUG:jieba:Building prefix dict from /content/dict.txt.big ...
Dumping model to file cache /tmp/jieba.u501edca284da514cb68b53a20324f4e3.cache
DEBUG:jieba:Dumping model to file cache /tmp/jieba.u501edca284da514cb68b53a20324f4e3.cache
Loading model cost 2.470 seconds.
DEBUG:jieba:Loading model cost 2.470 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.

In [ ]:
corpus = [] #訓練語料
for c in content_cut:
  corpus += [s.lstrip().rstrip() for s in c.split("\n") if s.count(" ") >= 2]
corpus

['安安',
 '美劇 絕命 毒師裡面 到 後期 老白 殺人 都 用 溶解 屍體 把 屍體 藏 起來',
 '想問 這招 在 現實 世界 真的 有 可能 嗎',
 '如果 真的 可以 的話 那 殺人 完再 把 屍體 溶解 不 就 不會 被 發現 惹',
 '有沒有 八卦',
 '--',
 '板上 的 30nm BMI39.87 + 的 中秋 胖魯宅們',
 '晚上 好',
 '稍早 阿肥 回到 家中',
 '一進 門口 就 看到 有 生物 趴著',
 '還擺著 一副 臭臉 在 那 ......',
 '眼見 這廝 的 眼神 如此 有事',
 '外加 方才 也 沒到 門口 迎接 阿肥',
 '嚇得 我 趕緊 拿出 罐頭 給 牠',
 '享用 完 罐頭 後 貓貓 還是 跑 回原 位置 QQ',
 '但 至少 眼神 柔和 多 了',
 '只是 才 吃 完晚 膳',
 '貓貓 就 回去 躺 在 那 還擺出 肥宅 姿勢',
 '明明 飯後 就是 該 起身 動一動 幫助 消化',
 '且 這 半年 來 牠 還胖 了 0.7 kg ......',
 '貓貓 難道 都 不會 煩惱 身軀 的 變化 嗎',
 'づ ・ ω ・ づ',
 '無用 的 肥宅貓',
 '羅馬不是 一天 造成 的 QQ',
 '--',
 'Ho 77777',
 '明明 就 超 cute',
 '喔 挖 鼻',
 '等 養狗 的 自己 不 74 雜種狗 在 說 吧',
 '※ 編輯 k44754 101.9 65.186 臺灣 09 26 2019 19 03 02',
 '大家 好 大家 晚安',
 '小弟 薩到 對面 的 女同事',
 '想 說 趁現在 買一送一 趕緊 獻上 一杯 我 的 愛心',
 '我問 她 想 喝 什麼 她 說 你 買 的 我 都 可以',
 'So ..',
 '問題 來 了',
 '我 只要 避開 最雷 的 那 一樣 就 勝券在握 了',
 '究竟 ..',
 '星巴克 最 難喝 的 飲料 是 哪 一樣',
 '--',
 '是 醬子 的',
 '本城 武 不知 為何',
 '睡前 沒 尻 尻 當晚 我 看 是 不用 睡 而且 會 很 難受',
 '所以 今天 睡前',
 '都 會 偷偷 的',
 '照 慣例 一下',
 '嘻',
 '欸',
 '貓貓 怎麼 一臉',
 '這樣 看 我 的話',
 '可能 要 兩次 才能 睡 噢',
 '嘻嘻',
 '--',
 '這 什麼 到底 什麼 優文',
 'OOOOOO',
 '--',
 '之前 一直 聽 身邊 果粉 歌頌 Mac 多棒 多 好',
 '就 想 說 買個 二手 Mac 體驗 看看',
 '應該 不會 很貴 吧',
 '結果 上 拍賣 一看',
 '不得了',
 '15 年 以上 就算 Air',
 '二手 三萬 起跳',
 '更 誇張 是',
 '2011 年 的 MBP',
 '還能 賣 一萬',
 '2011 年 我 記得 是 三代 intel 吧',
 'Windows 筆電 2011 年 的 到 現在 也 只 剩 幾千 的 價格',
 '為 什麼 Macbook 可以 這麼 誇張',
 'MacBook 到底 是 哪裡 可以 這麼 保值',
 '都 快 十年 的 電腦 了',
 '有沒有 八卦',
 '-----',
 'Sent from JPTT on my HMD Global Nokia 8.1',
 '--',
 '幹 二代 還有 一萬 扯 不 扯',
 '※ 編輯 ray90910 61.60 221.122 臺灣 07 31 2019 18 17 15',
 '大家 晚上 好',
 '中秋 好',
 '很久沒 有 半夜 發文 了',
 '很久沒 有 跟 各位 廢宅 廝混 了',
 '想 請教 一下',
 '小圈圈 解散 了 嗎',
 '深夜 八卦 是不是 稍微 風氣 好 一點 了',
 '因該 沒有 打情罵俏 了 吧',
 '--',
 '※ 編輯 Dinenger 110.28 64.248 臺灣 09 13 2019 00 25 08',
 '太 可怕 了 吧 國民黨 喔 退出 就 黑名單 我',
 '※ 編輯 Dinenger 110.28 64.248 臺灣 09 13 2019 00 26 18',
 '1 媒體 來源 ETtoday 新聞 雲',
 '2 記者 署名 記者 鄒鎮宇 ／ 桃園 報導',
 '3 完整 新聞標題',
 '突然 變紅 線 他 離開 3hrs 停車 格 被 塗黑 恐吃紅單 里長 嘆氣 曝 真相',
 '4 完整 新聞 內文',
 '記者 鄒鎮宇 ／ 桃園 報導',
 '桃園 一名 車主 抱怨 他 將車 停 在 頂興 路段 的 停車 格內 沒想到 當他 回來 開車 時竟 發現 停車',
 '格 被 黑漆 塗黑 旁邊 還畫 上 紅線 讓 他 看到 當場 爆氣 倘若 因此 被 開單 到底 要算 誰 的 對',
 '此 當地 里長 表示 該 停車位 多次 被 舉報 且 要 施工 早有 標示',
 '一名 民眾 15 日到 桃園 頂興 路段 停車 離開 3 小時 再 回來 立刻 發現 停車 格 本來 的 白線 被 塗黑',
 '讓 他 當場 傻眼 玻璃 前放著 大大的 電話號碼 有 想到 打 的 電話 通知 移車 嗎 試問 我 被',
 '開單 或 檢舉 要 找 誰 討 呢',
 '▲ ▼ 原 PO 發現 停車 格 被 塗黑 當場 氣炸 圖 ／ 翻攝 爆怨 公社',
 '此外 該 停車 格 地上 用 白漆 噴寫 5 月 16 日至 19 日 施工 車格 取消 由於 日期 經過 3 個 月 之',
 '久 讓 該 名 車主 完全 無法 聯想 到 道路 要 施工 才 會將 車輛 臨停 停車 格 離開 打電話 詢問',
 '里長 得到 的 結果 卻是 推託 裝傻 不 知道 沒 通知 沒收 到 公 文說 要 施工 態度 非常 不',
 '佳',
 '龜 山區 山德 里長 表示 該 停車位 早已 被民眾 舉報 多次 有人 白天 停 自家 轎車 晚上 用 大卡',
 '車的 車輪 佔位 人家 要 出來 右轉 都 看不到 車子 另外 由於 該車 格 位於 路口 轉彎 10',
 '公尺 處 本 就 不該 設有 容易 影響 交通安全',
 '交通局 停管局 科科長 魏光譽 表示 現場 本 就 設有 警告 並且 早 預告 施工 禁停 施 工時 車',
 '主的車 還是 停 在 這裡 我們 已經 聯繫 多次 無效 轉至 轄區 員警 來 聯繫 車主 也 是 聯繫 不上',
 '他 也 強調 不會 對 該 名 車主 開罰 倘若 民眾 有 收到 罰單 可 到 監理 站 提出 申訴',
 '5 完整 新聞 連結 或 短 網址',
 '6 備註',
 '蛤 還 可 提出 申訴 難怪 台灣 交通 就是 爛 字 可言',
 '呵呵 沒 劃線 的 路口 或劃 不到 10 公尺 紅線 的 都 能 強制 開單 了 還申 啥 訴 P',
 '--',
 '之前 加入 一個 學長 創 的 考 研究所 互相 加油 群組',
 '說 什麼 會 定期 發 考古題 和 解題',
 '結果 根本 屁 學長 沒事 傳 一些 什麼 香港 新聞 中秋節 快樂 那些',
 '跟 研究所 半點 毛 都 沒關係 想 退群 又 怕 被 貼標籤',
 '怎麼辦',
 '--',
 '乳提',
 '肥肥 我要 成為 大 魔導 士 了',
 '開始 有種 想 用 交友 軟體 的 念頭',
 '但 又 覺得 用 了 那個 心中 的 那個 堅持 就 輸 了',
 '難道 想 堅持 處男 情節 留給 另一半 最 真實 的 自己',
 '錯 了 嗎',
 '有沒有 八卦',
 '--',
 '+ smile ≠ ☺',
 '+ sad ≠ ☹',
 '+ cloud ≠ ☁',
 '+ star ≠',
 '+ airplane ≠ ✈',
 '--',
 '依稀記得 以前 學生 時期 搭 捷運 的 時候',
 '不管 是 書包 多麼 重 打球 多麼 累',
 '在 捷運 上 站 個 四十分鐘 都 不是 問題',
 '沒想到 今天 只是 背 包裝 個 幾本書',
 '一 上 捷運 就 覺得 他媽 超累 想要 馬上 找 位子 坐',
 '這樣 是不是 老 了 嗚嗚 嗚嗚',
 '--']

In [ ]:
from keras.preprocessing.text import Tokenizer #語料計算套件
tok = Tokenizer()
tok.fit_on_texts(corpus)
tok.word_index

{'的': 1,
 '了': 2,
 '就': 3,
 '都': 4,
 '被': 5,
 '我': 6,
 '是': 7,
 '停車': 8,
 '在': 9,
 '想': 10,
 '格': 11,
 '有': 12,
 '好': 13,
 '該': 14,
 '什麼': 15,
 '要': 16,
 '到': 17,
 '用': 18,
 '嗎': 19,
 '不': 20,
 '說': 21,
 '吧': 22,
 '他': 23,
 '施工': 24,
 '≠': 25,
 '可以': 26,
 '那': 27,
 '不會': 28,
 '發現': 29,
 '八卦': 30,
 '也': 31,
 '貓貓': 32,
 '※': 33,
 '編輯': 34,
 '臺灣': 35,
 '2019': 36,
 '上': 37,
 '年': 38,
 '新聞': 39,
 '桃園': 40,
 '塗黑': 41,
 '里長': 42,
 '車主': 43,
 '屍體': 44,
 '有沒有': 45,
 '晚上': 46,
 '來': 47,
 '09': 48,
 '大家': 49,
 '沒': 50,
 '會': 51,
 '到底': 52,
 '結果': 53,
 '15': 54,
 '2011': 55,
 '記者': 56,
 '／': 57,
 '3': 58,
 '完整': 59,
 '離開': 60,
 '停': 61,
 '讓': 62,
 '當場': 63,
 '開單': 64,
 '表示': 65,
 '多次': 66,
 '個': 67,
 '聯繫': 68,
 '捷運': 69,
 '殺人': 70,
 '溶解': 71,
 '把': 72,
 '真的': 73,
 '可能': 74,
 '的話': 75,
 '中秋': 76,
 '阿肥': 77,
 '門口': 78,
 '看到': 79,
 '眼神': 80,
 '趕緊': 81,
 '罐頭': 82,
 '牠': 83,
 '還是': 84,
 'qq': 85,
 '但': 86,
 '多': 87,
 '只是': 88,
 '才': 89,
 '明明': 90,
 '就是': 91,
 '且': 92,
 '這': 93,
 '難道': 94,
 'づ': 95,
 '・': 96,
 '喔': 97,
 '自己': 98,
 '26': 99,
 '19': 100,
 '她': 101,
 '問題': 102,
 '一樣': 103,
 '最': 104,
 '睡前': 105,
 '尻': 106,
 '看': 107,
 '睡': 108,
 '今天': 109,
 '一下': 110,
 '這樣': 111,
 '之前': 112,
 'mac': 113,
 '二手': 114,
 '誇張': 115,
 '一萬': 116,
 'macbook': 117,
 '這麼': 118,
 '1': 119,
 '扯': 120,
 '18': 121,
 '很久沒': 122,
 '跟': 123,
 '是不是': 124,
 'dinenger': 125,
 '110': 126,
 '28': 127,
 '64': 128,
 '248': 129,
 '13': 130,
 '00': 131,
 '鄒鎮宇': 132,
 '報導': 133,
 '一名': 134,
 '頂興': 135,
 '路段': 136,
 '沒想到': 137,
 '回來': 138,
 '紅線': 139,
 '倘若': 140,
 '誰': 141,
 '對': 142,
 '停車位': 143,
 '舉報': 144,
 '民眾': 145,
 '通知': 146,
 '或': 147,
 '找': 148,
 '5': 149,
 '月': 150,
 '由於': 151,
 '名': 152,
 '路口': 153,
 '10': 154,
 '公尺': 155,
 '本': 156,
 '設有': 157,
 '可': 158,
 '站': 159,
 '提出': 160,
 '申訴': 161,
 '學長': 162,
 '研究所': 163,
 '又': 164,
 '覺得': 165,
 '那個': 166,
 '堅持': 167,
 '多麼': 168,
 '嗚嗚': 169,
 '安安': 170,
 '美劇': 171,
 '絕命': 172,
 '毒師裡面': 173,
 '後期': 174,
 '老白': 175,
 '藏': 176,
 '起來': 177,
 '想問': 178,
 '這招': 179,
 '現實': 180,
 '世界': 181,
 '如果': 182,
 '完再': 183,
 '惹': 184,
 '板上': 185,
 '30nm': 186,
 'bmi39': 187,
 '87': 188,
 '胖魯宅們': 189,
 '稍早': 190,
 '回到': 191,
 '家中': 192,
 '一進': 193,
 '生物': 194,
 '趴著': 195,
 '還擺著': 196,
 '一副': 197,
 '臭臉': 198,
 '眼見': 199,
 '這廝': 200,
 '如此': 201,
 '有事': 202,
 '外加': 203,
 '方才': 204,
 '沒到': 205,
 '迎接': 206,
 '嚇得': 207,
 '拿出': 208,
 '給': 209,
 '享用': 210,
 '完': 211,
 '後': 212,
 '跑': 213,
 '回原': 214,
 '位置': 215,
 '至少': 216,
 '柔和': 217,
 '吃': 218,
 '完晚': 219,
 '膳': 220,
 '回去': 221,
 '躺': 222,
 '還擺出': 223,
 '肥宅': 224,
 '姿勢': 225,
 '飯後': 226,
 '起身': 227,
 '動一動': 228,
 '幫助': 229,
 '消化': 230,
 '半年': 231,
 '還胖': 232,
 '0': 233,
 '7': 234,
 'kg': 235,
 '煩惱': 236,
 '身軀': 237,
 '變化': 238,
 'ω': 239,
 '無用': 240,
 '肥宅貓': 241,
 '羅馬不是': 242,
 '一天': 243,
 '造成': 244,
 'ho': 245,
 '77777': 246,
 '超': 247,
 'cute': 248,
 '挖': 249,
 '鼻': 250,
 '等': 251,
 '養狗': 252,
 '74': 253,
 '雜種狗': 254,
 'k44754': 255,
 '101': 256,
 '9': 257,
 '65': 258,
 '186': 259,
 '03': 260,
 '02': 261,
 '晚安': 262,
 '小弟': 263,
 '薩到': 264,
 '對面': 265,
 '女同事': 266,
 '趁現在': 267,
 '買一送一': 268,
 '獻上': 269,
 '一杯': 270,
 '愛心': 271,
 '我問': 272,
 '喝': 273,
 '你': 274,
 '買': 275,
 'so': 276,
 '只要': 277,
 '避開': 278,
 '最雷': 279,
 '勝券在握': 280,
 '究竟': 281,
 '星巴克': 282,
 '難喝': 283,
 '飲料': 284,
 '哪': 285,
 '醬子': 286,
 '本城': 287,
 '武': 288,
 '不知': 289,
 '為何': 290,
 '當晚': 291,
 '不用': 292,
 '而且': 293,
 '很': 294,
 '難受': 295,
 '所以': 296,
 '偷偷': 297,
 '照': 298,
 '慣例': 299,
 '嘻': 300,
 '欸': 301,
 '怎麼': 302,
 '一臉': 303,
 '兩次': 304,
 '才能': 305,
 '噢': 306,
 '嘻嘻': 307,
 '優文': 308,
 'oooooo': 309,
 '一直': 310,
 '聽': 311,
 '身邊': 312,
 '果粉': 313,
 '歌頌': 314,
 '多棒': 315,
 '買個': 316,
 '體驗': 317,
 '看看': 318,
 '應該': 319,
 '很貴': 320,
 '拍賣': 321,
 '一看': 322,
 '不得了': 323,
 '以上': 324,
 '就算': 325,
 'air': 326,
 '三萬': 327,
 '起跳': 328,
 '更': 329,
 'mbp': 330,
 '還能': 331,
 '賣': 332,
 '記得': 333,
 '三代': 334,
 'intel': 335,
 'windows': 336,
 '筆電': 337,
 '現在': 338,
 '只': 339,
 '剩': 340,
 '幾千': 341,
 '價格': 342,
 '為': 343,
 '哪裡': 344,
 '保值': 345,
 '快': 346,
 '十年': 347,
 '電腦': 348,
 'sent': 349,
 'from': 350,
 'jptt': 351,
 'on': 352,
 'my': 353,
 'hmd': 354,
 'global': 355,
 'nokia': 356,
 '8': 357,
 '幹': 358,
 '二代': 359,
 '還有': 360,
 'ray90910': 361,
 '61': 362,
 '60': 363,
 '221': 364,
 '122': 365,
 '07': 366,
 '31': 367,
 '17': 368,
 '半夜': 369,
 '發文': 370,
 '各位': 371,
 '廢宅': 372,
 '廝混': 373,
 '請教': 374,
 '小圈圈': 375,
 '解散': 376,
 '深夜': 377,
 '稍微': 378,
 '風氣': 379,
 '一點': 380,
 '因該': 381,
 '沒有': 382,
 '打情罵俏': 383,
 '25': 384,
 '08': 385,
 '太': 386,
 '可怕': 387,
 '國民黨': 388,
 '退出': 389,
 '黑名單': 390,
 '媒體': 391,
 '來源': 392,
 'ettoday': 393,
 '雲': 394,
 '2': 395,
 '署名': 396,
 '新聞標題': 397,
 '突然': 398,
 '變紅': 399,
 '線': 400,
 '3hrs': 401,
 '恐吃紅單': 402,
 '嘆氣': 403,
 '曝': 404,
 '真相': 405,
 '4': 406,
 '內文': 407,
 '抱怨': 408,
 '將車': 409,
 '格內': 410,
 '當他': 411,
 '開車': 412,
 '時竟': 413,
 '黑漆': 414,
 '旁邊': 415,
 '還畫': 416,
 '爆氣': 417,
 '因此': 418,
 '要算': 419,
 '此': 420,
 '當地': 421,
 '早有': 422,
 '標示': 423,
 '日到': 424,
 '小時': 425,
 '再': 426,
 '立刻': 427,
 '本來': 428,
 '白線': 429,
 '傻眼': 430,
 '玻璃': 431,
 '前放著': 432,
 '大大的': 433,
 '電話號碼': 434,
 '想到': 435,
 '打': 436,
 '電話': 437,
 '移車': 438,
 '試問': 439,
 '檢舉': 440,
 '討': 441,
 '呢': 442,
 '▲': 443,
 '▼': 444,
 '原': 445,
 'po': 446,
 '氣炸': 447,
 '圖': 448,
 '翻攝': 449,
 '爆怨': 450,
 '公社': 451,
 '此外': 452,
 '地上': 453,
 '白漆': 454,
 '噴寫': 455,
 '16': 456,
 '日至': 457,
 '日': 458,
 '車格': 459,
 '取消': 460,
 '日期': 461,
 '經過': 462,
 '之': 463,
 '久': 464,
 '完全': 465,
 '無法': 466,
 '聯想': 467,
 '道路': 468,
 '會將': 469,
 '車輛': 470,
 '臨停': 471,
 '打電話': 472,
 '詢問': 473,
 '得到': 474,
 '卻是': 475,
 '推託': 476,
 '裝傻': 477,
 '知道': 478,
 '沒收': 479,
 '公': 480,
 '文說': 481,
 '態度': 482,
 '非常': 483,
 '佳': 484,
 '龜': 485,
 '山區': 486,
 '山德': 487,
 '早已': 488,
 '被民眾': 489,
 '有人': 490,
 '白天': 491,
 '自家': 492,
 '轎車': 493,
 '大卡': 494,
 '車的': 495,
 '車輪': 496,
 '佔位': 497,
 '人家': 498,
 '出來': 499,
 '右轉': 500,
 '看不到': 501,
 '車子': 502,
 '另外': 503,
 '該車': 504,
 '位於': 505,
 '轉彎': 506,
 '處': 507,
 '不該': 508,
 '容易': 509,
 '影響': 510,
 '交通安全': 511,
 '交通局': 512,
 '停管局': 513,
 '科科長': 514,
 '魏光譽': 515,
 '現場': 516,
 '警告': 517,
 '並且': 518,
 '早': 519,
 '預告': 520,
 '禁停': 521,
 '施': 522,
 '工時': 523,
 '車': 524,
 '主的車': 525,
 '這裡': 526,
 '我們': 527,
 '已經': 528,
 '無效': 529,
 '轉至': 530,
 '轄區': 531,
 '員警': 532,
 '不上': 533,
 '強調': 534,
 '開罰': 535,
 '收到': 536,
 '罰單': 537,
 '監理': 538,
 '連結': 539,
 '短': 540,
 '網址': 541,
 '6': 542,
 '備註': 543,
 '蛤': 544,
 '還': 545,
 '難怪': 546,
 '台灣': 547,
 '交通': 548,
 '爛': 549,
 '字': 550,
 '可言': 551,
 '呵呵': 552,
 '劃線': 553,
 '或劃': 554,
 '不到': 555,
 '能': 556,
 '強制': 557,
 '還申': 558,
 '啥': 559,
 '訴': 560,
 'p': 561,
 '加入': 562,
 '一個': 563,
 '創': 564,
 '考': 565,
 '互相': 566,
 '加油': 567,
 '群組': 568,
 '定期': 569,
 '發': 570,
 '考古題': 571,
 '和': 572,
 '解題': 573,
 '根本': 574,
 '屁': 575,
 '沒事': 576,
 '傳': 577,
 '一些': 578,
 '香港': 579,
 '中秋節': 580,
 '快樂': 581,
 '那些': 582,
 '半點': 583,
 '毛': 584,
 '沒關係': 585,
 '退群': 586,
 '怕': 587,
 '貼標籤': 588,
 '怎麼辦': 589,
 '乳提': 590,
 '肥肥': 591,
 '我要': 592,
 '成為': 593,
 '大': 594,
 '魔導': 595,
 '士': 596,
 '開始': 597,
 '有種': 598,
 '交友': 599,
 '軟體': 600,
 '念頭': 601,
 '心中': 602,
 '輸': 603,
 '處男': 604,
 '情節': 605,
 '留給': 606,
 '另一半': 607,
 '真實': 608,
 '錯': 609,
 'smile': 610,
 '☺': 611,
 'sad': 612,
 '☹': 613,
 'cloud': 614,
 '☁': 615,
 'star': 616,
 'airplane': 617,
 '✈': 618,
 '依稀記得': 619,
 '以前': 620,
 '學生': 621,
 '時期': 622,
 '搭': 623,
 '時候': 624,
 '不管': 625,
 '書包': 626,
 '重': 627,
 '打球': 628,
 '累': 629,
 '四十分鐘': 630,
 '不是': 631,
 '背': 632,
 '包裝': 633,
 '幾本書': 634,
 '一': 635,
 '他媽': 636,
 '超累': 637,
 '想要': 638,
 '馬上': 639,
 '位子': 640,
 '坐': 641,
 '老': 642}

In [ ]:
corpus_seq = tok.texts_to_sequences(corpus)
V = len(tok.word_index) + 1 #語料量
dim = 100 #降維成多少特徵
window = 2 #取上文下文

In [ ]:
from keras.models import Sequential #模型支架
import keras.backend as K
from keras.layers import Embedding, Lambda, Dense
cbow = Sequential()
cbow.add(Embedding(V, dim, input_length=window*2))
cbow.add(Lambda(lambda x: K.mean(x, axis=1)))
cbow.add(Dense(V, activation="softmax"))
cbow.summary() #查看模型架構

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 4, 100)            64300

 lambda (Lambda)             (None, 100)               0

 dense (Dense)               (None, 643)               64943

=================================================================
Total params: 129243 (504.86 KB)
Trainable params: 129243 (504.86 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
cbow.compile(loss="categorical_crossentropy", optimizer="adam") #建立模型

In [ ]:
from keras.preprocessing import sequence #序列套件
from keras.utils import to_categorical #One-hot encoding
def generate_data(corpus, window, V):
  for sentence in corpus:
    L = len(sentence)
    for i, word in enumerate(sentence):
      contexts = [] #上下文
      label = [] #機率
      start = i - window #開始
      end = i + window #結束
      c = [sentence[j] for j in range(start, end + 1) if not j == i and 0 <= j < L]
      contexts.append(c)
      label.append(word)
      x = sequence.pad_sequences(contexts, maxlen = window * 2)
      y = to_categorical(label, V)
      yield (x, y)

In [ ]:
g = generate_data(corpus_seq, window, V)
g.__next__()

(array([[0, 0, 0, 0]], dtype=int32),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]], dtype=float32))

In [ ]:
for epoch in range(10):
  loss = 0.
  for x, y in generate_data(corpus_seq, window, V):
    l = cbow.train_on_batch(x, y) #訓練模型
    loss += l
  print("epoch:", epoch)
  print("loss:", loss)
  print("*" * 50)

epoch: 0
loss: 6670.526853561401
**************************************************
epoch: 1
loss: 6375.774891376495
**************************************************
epoch: 2
loss: 6002.374831438065
**************************************************
epoch: 3
loss: 5517.767281293869
**************************************************
epoch: 4
loss: 4959.091503858566
**************************************************
epoch: 5
loss: 4379.1203489899635
**************************************************
epoch: 6
loss: 3806.8845297396183
**************************************************
epoch: 7
loss: 3256.5929431021214
**************************************************
epoch: 8
loss: 2741.6017807871103
**************************************************
epoch: 9
loss: 2277.032280355692
**************************************************

In [ ]:
f = open("word2vec.txt", "w", encoding="utf-8")
f.write("{} {}\n".format(V - 1, dim))
weights = cbow.get_weights()[0]
for word, i in tok.word_index.items():
  vec = " ".join(map(str, list(weights[i])))
  f.write("{} {}\n".format(word, vec))
f.close()

In [1]:
import gensim
w2v = gensim.models.KeyedVectors.load_word2vec_format("word2vec.txt", binary=False)

In [2]:
all = len(w2v.key_to_index)
print(f"語料量有 {all} 個詞")

語料量有 642 個詞

In [3]:
w2v.most_similar("且")

[('這', 0.5810895562171936),
 ('舉報', 0.5305156707763672),
 ('貼標籤', 0.5105465650558472),
 ('到底', 0.5097517967224121),
 ('早已', 0.49703913927078247),
 ('塗黑', 0.47824758291244507),
 ('惹', 0.4765941798686981),
 ('半年', 0.45977136492729187),
 ('多次', 0.44200989603996277),
 ('黑漆', 0.4321693181991577)]

In [4]:
word = "捷運"#@param {type:"string"}
print(word, "長這樣:")
w2v[word]

捷運 長這樣:

array([-0.47996187,  0.73570865,  0.3277341 , -0.7456761 ,  0.16083609,
        0.1595168 , -0.310021  , -0.63732785, -0.72869515,  0.31115544,
       -0.32475996,  0.25620463,  0.20138544,  0.3984571 , -0.12057469,
        0.01149212,  0.5962413 ,  0.34213147,  0.670972  , -0.32170945,
       -0.20425221, -0.5374604 ,  0.08871066,  0.5077034 ,  0.35019302,
        0.50595814, -0.00576012,  0.5424007 ,  0.7067157 ,  0.1629787 ,
        0.6316644 , -0.4142171 ,  0.74703354,  0.24764945,  0.7046723 ,
       -0.26374033, -0.04697875,  0.08571845,  0.36865294, -0.11452562,
        0.42694333,  0.04206524,  0.02034544, -0.02940158, -0.8374156 ,
        0.6558914 , -0.07585112,  0.24365322, -0.5886401 , -0.02104452,
        0.26384732,  0.31769776, -0.40545747, -0.38368788, -0.6292438 ,
        0.32939327,  0.32334533,  0.48463586, -0.72527564,  0.68223774,
        0.00649907,  0.10010861,  0.4014573 ,  0.07116267, -0.24178421,
       -0.1954925 ,  0.22103055,  0.0111903 , -0.20102309,  0.46052086,
       -0.14951509, -0.15639757, -0.29529285,  0.30202147,  0.0016331 ,
       -0.07327404,  0.03702268,  0.34720483, -0.47028396,  0.22865361,
        0.2959652 , -0.1417722 ,  0.22180843, -0.3440878 , -0.3280608 ,
       -0.07609144,  0.5888261 , -0.00190059, -0.5117148 , -0.8104838 ,
        0.25185424, -0.4639593 , -0.06514323,  0.21093103, -0.2803411 ,
       -0.14608401,  0.09861253,  0.00363467, -0.35855728,  0.08889189],
      dtype=float32)

In [12]:
text1 = "我" #@param {type:"string"}
text2 = "他" #@param {type:"string"}
w2v.similarity(text1, text2)

-0.123063795

In [9]:
text1 = "我" #@param {type:"string"}
text2 = "他" #@param {type:"string"}
text3 = "她" #@param {type:"string"}
text4 = "阿肥" #@param {type:"string"}

notmatch = w2v.doesnt_match([text1, text2, text3, text4])
print("不是同一掛的:", notmatch)

不是同一掛的: 他

#預處理工具

In [ ]:
!pip install opencc-python-reimplemented #安裝簡體轉繁體套件

Collecting opencc-python-reimplemented
  Downloading opencc_python_reimplemented-0.1.7-py2.py3-none-any.whl (481 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 481.8/481.8 kB 5.7 MB/s eta 0:00:00
Installing collected packages: opencc-python-reimplemented
Successfully installed opencc-python-reimplemented-0.1.7

In [ ]:
import chardet #編碼偵測套件
with open("redmansion_big5.txt", "rb") as f:
  content = f.read()
  contents = chardet.detect(content)
print(contents)

with open("redmansion_big5_utf-8.txt", "w", encoding="utf-8") as f:
  utf8 = content.decode(contents["encoding"], errors="ignore")
  f.write(utf8)
print("*簡體*", utf8[-1000:])

{'encoding': 'Big5', 'confidence': 0.99, 'language': 'Chinese'}
*簡體* 麼？」那僧說：「情緣尚未全結，倒是那蠢物已經回來了。還得把他送還原所，將他的後事敘明，不枉他下世一回。」士隱聽了，便供手而別。那僧道仍攜了玉到青埂峰下，將「寶玉」安放在女媧煉石補天之處，各自雲遊而去。從此後：天外書傳天外事，兩番人作一番人。」

　　這一日，空空道人又從青埂峰前經過，見那補天未用之石仍在那裡，上面字跡依然如舊，又從頭的細細看了一遍，見後面偈文後又歷敘了多少收緣結果的話頭，便點頭嘆道：「我從前見石兄這段奇文，原說可以聞世傳奇，所以曾經抄錄，但未見返本還原。不知何時復有此一佳話？方知石兄下凡一次，磨出光明，修成圓覺，也可謂無復遺憾了。只怕年深日久，字跡模糊，反有舛錯，不如我再抄錄一番，尋個世上清閒無事的人，託他傳遍，知道奇而不奇，俗而不俗，真而不真，假而不假。或者塵夢勞人，聊倩鳥呼歸去；山靈好客，更從石化飛來，亦未可知。」想畢，便又抄了，仍袖至那繁華昌盛的地方，遍尋了一番，不是建功立業之人，即係饒口謀衣之輩，那有閒情更去和石頭饒舌。直尋到急流津覺迷度口，草庵中睡著一個人，因想他必是閒人，便要將這抄錄的《石頭記》給他看看。那知那人再叫不醒。空空道人復又使勁拉他，才慢慢的開眼坐起，便草草一看，仍舊擲下道：「這事我早已親見盡知。你這抄錄的尚無舛錯。我只指與你一個人，託他傳去，便可歸結這一新鮮公案了。」空空道人忙問何人，那人道：「你須待某年、某月、某日、某時，到一個悼紅軒中，有個曹雪芹先生，只說賈雨村言，託他如此如此。」說畢，仍舊睡下了。

　　那空空道人牢牢記著此言，又不知過了幾世幾劫，果然有個悼紅軒，見那曹雪芹先生正在那裡翻閱歷來的古史。空空道人便將賈雨村言了，方把這《石頭記》示看。那雪芹先生笑道：「果然是『賈雨村言』了！」空空道人便問：「先生何以認得此人，便肯替他傳述？」曹雪芹先生笑道：「說你空，原來你肚裡果然空空。既是假語村言，但無魯魚亥豕以及背謬矛盾之處，樂得與二三同志，酒餘飯飽，雨夕燈窗之下，同消寂寞，又不必大人先生品題傳世。似你這樣尋根問底，便是刻舟求劍、膠柱鼓瑟了。」那空空道人聽了，仰天大笑，擲下抄本，飄然而去。一面走著，口中說道：「果然是敷衍荒唐！不但作者不知，抄者不知，並閱者也不知。不過遊戲筆墨，陶情適性而已！」後人見了這本奇傳，亦曾題過四句偈語，為作者緣起之言更轉一竿頭云：

　　說到辛酸處，荒唐愈可悲。由來同一夢，休笑世人痴！

In [ ]:
import chardet
from opencc import OpenCC #簡體轉繁體套件
with open("redmansion_gbk.txt", "rb") as f:
  content = f.read()
print(chardet.detect(content))

cc = OpenCC('s2tw')
converted = cc.convert(utf8)

with open("redmansion_gbk.txt", "w", encoding="utf-8") as f:
  f.write(converted)
print("*繁體*", converted[-1000:])

{'encoding': 'GB2312', 'confidence': 0.99, 'language': 'Chinese'}
*繁體* 麼？」那僧說：「情緣尚未全結，倒是那蠢物已經回來了。還得把他送還原所，將他的後事敘明，不枉他下世一回。」士隱聽了，便供手而別。那僧道仍攜了玉到青埂峰下，將「寶玉」安放在女媧煉石補天之處，各自雲遊而去。從此後：天外書傳天外事，兩番人作一番人。」

　　這一日，空空道人又從青埂峰前經過，見那補天未用之石仍在那裡，上面字跡依然如舊，又從頭的細細看了一遍，見後面偈文後又歷敘了多少收緣結果的話頭，便點頭嘆道：「我從前見石兄這段奇文，原說可以聞世傳奇，所以曾經抄錄，但未見返本還原。不知何時復有此一佳話？方知石兄下凡一次，磨出光明，修成圓覺，也可謂無復遺憾了。只怕年深日久，字跡模糊，反有舛錯，不如我再抄錄一番，尋個世上清閒無事的人，託他傳遍，知道奇而不奇，俗而不俗，真而不真，假而不假。或者塵夢勞人，聊倩鳥呼歸去；山靈好客，更從石化飛來，亦未可知。」想畢，便又抄了，仍袖至那繁華昌盛的地方，遍尋了一番，不是建功立業之人，即係饒口謀衣之輩，那有閒情更去和石頭饒舌。直尋到急流津覺迷度口，草菴中睡著一個人，因想他必是閒人，便要將這抄錄的《石頭記》給他看看。那知那人再叫不醒。空空道人復又使勁拉他，才慢慢的開眼坐起，便草草一看，仍舊擲下道：「這事我早已親見盡知。你這抄錄的尚無舛錯。我只指與你一個人，託他傳去，便可歸結這一新鮮公案了。」空空道人忙問何人，那人道：「你須待某年、某月、某日、某時，到一個悼紅軒中，有個曹雪芹先生，只說賈雨村言，託他如此如此。」說畢，仍舊睡下了。

　　那空空道人牢牢記著此言，又不知過了幾世幾劫，果然有個悼紅軒，見那曹雪芹先生正在那裡翻閱歷來的古史。空空道人便將賈雨村言了，方把這《石頭記》示看。那雪芹先生笑道：「果然是『賈雨村言』了！」空空道人便問：「先生何以認得此人，便肯替他傳述？」曹雪芹先生笑道：「說你空，原來你肚裡果然空空。既是假語村言，但無魯魚亥豕以及背謬矛盾之處，樂得與二三同志，酒餘飯飽，雨夕燈窗之下，同消寂寞，又不必大人先生品題傳世。似你這樣尋根問底，便是刻舟求劍、膠柱鼓瑟了。」那空空道人聽了，仰天大笑，擲下抄本，飄然而去。一面走著，口中說道：「果然是敷衍荒唐！不但作者不知，抄者不知，並閱者也不知。不過遊戲筆墨，陶情適性而已！」後人見了這本奇傳，亦曾題過四句偈語，為作者緣起之言更轉一竿頭雲：

　　說到辛酸處，荒唐愈可悲。由來同一夢，休笑世人痴！